export { default as IndexPage } from "./IndexPage"
export { default as LoginPage } from "./LoginPage"
export { default as NotFoundPage } from "./NotFoundPage"
export { default as PostListPage } from "./PostListPage"
export { default as RegisterPage } from "./RegisterPage"
export { default as ViewPostPage } from "./ViewPostPage"
